### ISSUE TITLE
Could set node runtime other than 8.9 in serverless.yml?

### ISSUE THREAD

**Issue by xiechao06** [serverless-components/tencent-koa#28]

**Comment by roy-lau** [comment]
There are three options：
Nodejs6.10、Nodejs8.9、Nodejs12.16

**Comment by yugasun** [comment]
Actually four options:

```
Nodejs6.10、Nodejs8.9、Nodejs10.15、Nodejs12.16
```

**Comment by roy-lau** [comment]
> Actually four options:
> Nodejs6.10、Nodejs8.9、Nodejs10.15、Nodejs12.16

This is official
