### ISSUE TITLE
网关中的api前后端配置可以设置吗？

### ISSUE THREAD

**Issue by dxy2233** [serverless-components/tencent-koa#33]

**Comment by tinafangkunding** [comment]
您好，这个建议直接利用 api 网关组件来配置后端、前端。除了 scf 之后您需要哪种后端呢，是否需要 mock 等

**Comment by dxy2233** [comment]
> 您好，这个建议直接利用 api 网关组件来配置后端、前端。除了 scf 之后您需要哪种后端呢，是否需要 mock 等

api后端使用scf，mock功能可以在代码内实现，也不是很有必要。
我在控制台更改了网关服务下api前端的路径、名称、描述等，代码更新后重新部署把这些更改的配置全都重置了，所以每次部署上去后都要再更改一次。
看了下源码，该配置是写死的，能否开放呢？
